export type ToolCategory = "編碼與雜湊" | "威脅分析" | "網路與風險" | "密碼與驗證" | "鑑識與分析" | "CTF 工具";

export type ToolDefinition = {
  slug: string;
  name: string;
  englishName: string;
  description: string;
  category: ToolCategory;
  icon: string;
  tags: string[];
  featured?: boolean;
  status?: "new" | "popular";
  guide?: {
    intro: string;
    steps: [string, string, string];
    useCases: [string, string, string];
  };
};

export const categories: Array<{ name: ToolCategory; label: string }> = [
  { name: "編碼與雜湊", label: "ENCODE" },
  { name: "威脅分析", label: "THREAT INTEL" },
  { name: "網路與風險", label: "NETWORK" },
  { name: "密碼與驗證", label: "AUTH" },
  { name: "鑑識與分析", label: "FORENSICS" },
  { name: "CTF 工具", label: "CTF" },
];

export const toolCatalog: ToolDefinition[] = [
  {
    slug: "hash-generator",
    name: "雜湊產生器",
    englishName: "Hash Generator",
    description: "快速計算 SHA-1、SHA-256、SHA-384 與 SHA-512，適合比對檔案與事件證據。",
    category: "編碼與雜湊",
    icon: "#",
    tags: ["hash", "sha256", "checksum", "雜湊"],
    featured: true,
    status: "popular",
  },
  {
    slug: "base64-codec",
    name: "Base64 編解碼",
    englishName: "Base64 Codec",
    description: "正確處理 UTF-8 中文文字的 Base64 編碼與解碼。",
    category: "編碼與雜湊",
    icon: "64",
    tags: ["base64", "encode", "decode", "編碼"],
    featured: true,
  },
  {
    slug: "url-codec",
    name: "URL 編解碼",
    englishName: "URL Codec",
    description: "安全地編碼或還原查詢字串、路徑與特殊字元。",
    category: "編碼與雜湊",
    icon: "%",
    tags: ["url", "percent encoding", "decode"],
  },
  {
    slug: "hmac-generator",
    name: "HMAC 產生器",
    englishName: "HMAC Generator",
    description: "使用本機 Web Crypto 建立 HMAC-SHA256/384/512 訊息驗證碼。",
    category: "編碼與雜湊",
    icon: "H",
    tags: ["hmac", "signature", "sha256", "api"],
  },
  {
    slug: "sri-generator",
    name: "SRI 完整性雜湊",
    englishName: "SRI Hash Generator",
    description: "為前端資源產生 Subresource Integrity sha384 屬性值。",
    category: "編碼與雜湊",
    icon: "S",
    tags: ["sri", "integrity", "frontend", "supply chain"],
    status: "new",
  },
  {
    slug: "jwt-decoder",
    name: "JWT 解碼器",
    englishName: "JWT Decoder",
    description: "在本機檢視 JWT header、payload、到期時間與常見安全警訊。",
    category: "密碼與驗證",
    icon: "J",
    tags: ["jwt", "token", "oauth", "authentication"],
    featured: true,
    status: "popular",
  },
  {
    slug: "jwt-signature-verifier",
    name: "JWT／JWK 簽章驗證器",
    englishName: "JWT Signature Verifier",
    description: "使用本機 Web Crypto 驗證 HS、RS、PS、ES 系列 JWT 簽章，公開金鑰與 Secret 不會送出瀏覽器。",
    category: "密碼與驗證",
    icon: "✓J",
    tags: ["jwt verify", "jwk", "jwks", "oauth", "openid connect"],
    featured: true,
    status: "new",
    guide: {
      intro: "JWT 能被 Base64URL 解碼不代表簽章有效。本工具依 Header alg 選擇固定的 Web Crypto 驗章演算法，拒絕 alg=none，且不會自動從網路下載 JWKS。",
      steps: ["貼上完整三段式 JWT，再輸入 HS Secret 或可信來源提供的公開 JWK JSON。", "驗證後核對 alg、金鑰類型、簽章結果，以及 exp、nbf、iat 時間警告。", "簽章有效只代表內容未被該金鑰竄改；仍需由應用程式驗證 issuer、audience、nonce 與授權規則。"],
      useCases: ["排查 OAuth、OpenID Connect 與 API Gateway 的 JWT 驗章問題。", "在不把 Token 或金鑰傳到第三方網站的前提下核對簽章。", "分析 CTF、事件調查或測試環境中的 HS／RSA／ECDSA JWT。"],
    },
  },
  {
    slug: "password-generator",
    name: "安全密碼產生器",
    englishName: "Password Generator",
    description: "使用密碼學安全亂數產生器建立可自訂規則的強密碼。",
    category: "密碼與驗證",
    icon: "✦",
    tags: ["password", "random", "credential", "密碼"],
    featured: true,
  },
  {
    slug: "password-strength",
    name: "密碼強度檢查",
    englishName: "Password Strength Checker",
    description: "估算熵值並找出常見字串、重複模式與組成弱點。",
    category: "密碼與驗證",
    icon: "▰",
    tags: ["password", "entropy", "strength", "密碼強度"],
  },
  {
    slug: "otp-generator",
    name: "TOTP／HOTP 驗證碼",
    englishName: "TOTP & HOTP Generator",
    description: "使用本機 Web Crypto 依 RFC 4226／6238 計算一次性驗證碼，支援 SHA-1、SHA-256 與 SHA-512。",
    category: "密碼與驗證",
    icon: "OTP",
    tags: ["totp", "hotp", "mfa", "2fa", "rfc 6238"],
    featured: true,
    status: "new",
    guide: {
      intro: "TOTP 與 HOTP 是雙因素驗證常見的一次性密碼標準。本工具可離線重現 Authenticator 驗證碼，用來測試 MFA 串接、CTF 題目或核對伺服器實作。",
      steps: ["貼上服務提供的 Base32 Secret，選擇時間型 TOTP 或 Counter 型 HOTP。", "依服務端設定選擇驗證碼位數、HMAC 演算法與週期或 Counter。", "產生驗證碼後立即核對；TOTP 會隨時間週期失效，HOTP 使用後應遞增 Counter。"],
      useCases: ["測試 RFC 4226 HOTP 與 RFC 6238 TOTP 實作是否一致。", "排查 MFA、2FA 或 Authenticator 因時間偏差造成的驗證失敗。", "解答需要一次性密碼、Base32 或 HMAC 的資安與 CTF 題目。"],
    },
  },
  {
    slug: "ioc-extractor",
    name: "IOC 指標擷取器",
    englishName: "IOC Extractor",
    description: "從事件報告或 Log 一次擷取 IP、網域、URL、Email 與雜湊值。",
    category: "威脅分析",
    icon: "◎",
    tags: ["ioc", "ip", "domain", "hash", "threat intelligence"],
    featured: true,
    status: "popular",
  },
  {
    slug: "url-defanger",
    name: "URL Defang / Refang",
    englishName: "URL Defanger",
    description: "將可疑 URL 與 IP 去武器化，或還原分析報告中的安全格式。",
    category: "威脅分析",
    icon: "[.]",
    tags: ["defang", "refang", "url", "malware"],
    featured: true,
  },
  {
    slug: "entropy-calculator",
    name: "資料熵值計算器",
    englishName: "Entropy Calculator",
    description: "計算 Shannon entropy，協助辨識壓縮、加密或混淆內容。",
    category: "威脅分析",
    icon: "Σ",
    tags: ["entropy", "forensics", "malware", "shannon"],
  },
  {
    slug: "cidr-calculator",
    name: "IPv4 CIDR 計算器",
    englishName: "CIDR Calculator",
    description: "計算網路位址、廣播位址、遮罩、可用主機數與 IP 範圍。",
    category: "網路與風險",
    icon: "/",
    tags: ["cidr", "subnet", "ipv4", "network"],
    featured: true,
  },
  {
    slug: "ip-address-converter",
    name: "IP 位址轉換器",
    englishName: "IPv4 & IPv6 Address Converter",
    description: "正規化 IPv4／IPv6，並轉換成展開格式、整數、Hex、Binary 與 Reverse DNS 名稱。",
    category: "網路與風險",
    icon: "IP",
    tags: ["ipv4", "ipv6", "hex", "reverse dns", "network"],
    featured: true,
    status: "new",
    guide: {
      intro: "IP 位址在封包、Log、DNS 與 CTF 題目中常以不同格式出現。本工具同時處理 IPv4 與 IPv6，協助確認同一位址的正規化、整數與十六進位表示。",
      steps: ["輸入一個 IPv4 或 IPv6 位址；IPv6 可使用 :: 壓縮，也可保留成對方括號。", "按下解析與轉換，檢查正規化、完整展開、Decimal、Hex 與 Binary 結果。", "需要 PTR 查詢名稱時，複製產生的 in-addr.arpa 或 ip6.arpa Reverse DNS 名稱。"],
      useCases: ["正規化 SOC、Firewall、Proxy 與 Web Log 裡的 IPv6 位址。", "在惡意程式分析或 CTF 中轉換 IPv4 整數、Hex 與 Binary。", "產生 IPv4／IPv6 的 Reverse DNS PTR 查詢名稱。"],
    },
  },
  {
    slug: "ipv6-cidr-calculator",
    name: "IPv6 CIDR 計算器",
    englishName: "IPv6 CIDR Calculator",
    description: "計算 IPv6 prefix 的網路位址、範圍、位址數與 Reverse DNS zone，並輸出 RFC 5952 正規格式。",
    category: "網路與風險",
    icon: "/6",
    tags: ["ipv6", "cidr", "prefix", "subnet", "reverse dns"],
    featured: true,
    status: "new",
    guide: {
      intro: "IPv6 網段通常以 prefix length 表示，手動展開 128-bit 位址很容易出錯。本工具可離線計算網路邊界、完整範圍與 nibble-aligned Reverse DNS zone。",
      steps: ["輸入 IPv6 位址與 prefix，例如 2001:db8:1234:5678::1/64。", "計算後核對 RFC 5952 壓縮格式、完整展開格式與首末位址。", "若 prefix 為 4 的倍數，可複製產生的 ip6.arpa Reverse DNS zone。"],
      useCases: ["規劃 IPv6 subnet、ACL、Firewall 與 SIEM 網段條件。", "確認某個壓縮 IPv6 位址所屬的 prefix 範圍。", "產生 IPv6 PTR delegation 使用的 ip6.arpa zone。"],
    },
  },
  {
    slug: "ipv4-cidr-aggregator",
    name: "IPv4 CIDR 合併器",
    englishName: "IPv4 CIDR Aggregator",
    description: "合併重疊與相鄰的 IPv4 位址或 CIDR，輸出涵蓋相同範圍的最小網段清單。",
    category: "網路與風險",
    icon: "Σ/",
    tags: ["ipv4", "cidr aggregation", "subnet", "firewall", "acl"],
    featured: true,
    status: "new",
    guide: {
      intro: "Firewall、ACL、SIEM 與 Threat Intel 清單常累積大量重疊網段。本工具會在本機將它們轉成精確、無額外放寬範圍的最小 IPv4 CIDR 集合。",
      steps: ["每行貼上一個 IPv4 或 CIDR；單一 IP 會視為 /32，也支援逗號與 # 註解。", "執行後核對輸入筆數、實際涵蓋位址數與壓縮後的 CIDR 數量。", "複製結果到 Firewall、ACL 或 SIEM 前，仍應依設備語法與變更流程驗證。"],
      useCases: ["整理防火牆 allowlist、blocklist 與雲端 Security Group 網段。", "將 Threat Intel IP 清單去重並壓縮，減少規則數量。", "確認相鄰的 /25、/26 等網段能否安全合併成較短 prefix。"],
    },
  },
  {
    slug: "cvss-calculator",
    name: "CVSS v3.1 計算器",
    englishName: "CVSS v3.1 Calculator",
    description: "依 FIRST CVSS v3.1 基礎指標計算分數、嚴重度與 Vector。",
    category: "網路與風險",
    icon: "V",
    tags: ["cvss", "vulnerability", "risk", "cve"],
    featured: true,
    status: "new",
  },
  {
    slug: "security-headers-analyzer",
    name: "安全標頭分析器",
    englishName: "Security Headers Analyzer",
    description: "貼上 HTTP response headers，檢查 CSP、HSTS、Referrer-Policy 等防護與常見設定缺口。",
    category: "網路與風險",
    icon: "H:",
    tags: ["security headers", "csp", "hsts", "http", "web security"],
    featured: true,
    status: "new",
  },
  {
    slug: "csp-policy-analyzer",
    name: "CSP 政策深度分析器",
    englishName: "Content Security Policy Analyzer",
    description: "逐項檢查 Content-Security-Policy 的 script-src、object-src、base-uri、frame-ancestors 與常見寬鬆來源。",
    category: "網路與風險",
    icon: "CSP",
    tags: ["content security policy", "csp", "xss", "security headers", "frontend security"],
    featured: true,
    status: "new",
    guide: {
      intro: "CSP 是否存在只是第一步，unsafe-inline、unsafe-eval、wildcard、缺少 base-uri 或 frame-ancestors 都會影響實際防護。本工具離線拆解 policy 並區分阻斷缺口與強化建議。",
      steps: ["貼上完整 CSP Header 或只有 policy value；Report-Only Header 也可辨識。", "依分數、等級與逐項 findings 檢查腳本來源、plugin、base tag、表單與 iframe 限制。", "修改政策後重新分析，並在測試環境觀察瀏覽器 violation report，避免直接破壞正式功能。"],
      useCases: ["檢查網站、CDN 或 Cloudflare Response Header 的 CSP 強度。", "找出 unsafe-inline、unsafe-eval、data:、blob: 與 wildcard 等 XSS 風險。", "協助前端團隊逐步導入 nonce、hash、Trusted Types 與 deny-by-default CSP。"],
    },
  },
  {
    slug: "http-message-parser",
    name: "HTTP 訊息解析器",
    englishName: "HTTP Request & Response Parser",
    description: "解析原始 HTTP Request／Response、Headers、Query、Cookies 與表單 Body，並標示常見歧義與敏感欄位。",
    category: "網路與風險",
    icon: "HTTP",
    tags: ["http request", "http response", "burp suite", "headers", "web ctf"],
    featured: true,
    status: "new",
    guide: {
      intro: "從 Burp Suite、Proxy、封包或 Log 複製的原始 HTTP 訊息常包含多層資料。本工具不會重送請求，只在本機拆解起始行、標頭與常見 Body 格式。",
      steps: ["貼上完整 Request 或 Response，保留起始行與 Headers。", "按下解析後檢查 Method／Status、Query、Cookies、Body parameters 與重複 Headers。", "依警告確認 Content-Length、Transfer-Encoding 或敏感 Authorization 欄位是否需要進一步調查。"],
      useCases: ["整理 Burp Suite、mitmproxy 或封包擷取中的 HTTP 訊息。", "分析 Web CTF 的 Query、Cookie、Form Body 與 Request Smuggling 線索。", "在不對目標主機發送任何請求的前提下檢查可疑流量。"],
    },
  },
  {
    slug: "dns-message-decoder",
    name: "DNS 封包解碼器",
    englishName: "DNS Wire Message Decoder",
    description: "離線解析 Hex 或 Base64 DNS wire message，拆解 Header、Question、Answer 與常見 Resource Record。",
    category: "網路與風險",
    icon: "DNS",
    tags: ["dns packet", "dns decoder", "pcap", "wireshark", "malware"],
    featured: true,
    status: "new",
    guide: {
      intro: "DNS 封包在 PCAP、EDR、惡意程式設定與 CTF 中常以原始 Hex 或 Base64 出現。本工具不會送出 DNS 查詢，只依 wire format 拆解本機輸入。",
      steps: ["選擇 Hex 或 Base64，貼入從封包或紀錄擷取的完整 DNS message。", "解碼後檢查 Transaction ID、Flags、RCODE、Question 與各 Section 的 Resource Records。", "對照 TTL、A／AAAA／CNAME／MX／TXT 等資料；未知 Record 會保留為 Hex。"],
      useCases: ["分析 Wireshark、Zeek、Suricata 或惡意程式擷取出的 DNS payload。", "辨識 DNS tunneling、可疑 TXT record 與 CNAME 跳轉線索。", "解答需要手動閱讀 DNS name compression 或 wire format 的 CTF 題目。"],
    },
  },
  {
    slug: "email-header-analyzer",
    name: "Email Header 分析器",
    englishName: "Email Header Analyzer",
    description: "解析郵件標頭、傳遞節點與 SPF、DKIM、DMARC 驗證結果，協助調查釣魚郵件。",
    category: "威脅分析",
    icon: "@",
    tags: ["email", "header", "spf", "dkim", "dmarc", "phishing"],
    featured: true,
    status: "new",
  },
  {
    slug: "file-signature-checker",
    name: "檔案簽章辨識器",
    englishName: "File Signature Checker",
    description: "讀取本機檔案 Magic Bytes，辨識真實格式並比對副檔名，檔案內容不會上傳。",
    category: "鑑識與分析",
    icon: "0x",
    tags: ["magic bytes", "file signature", "forensics", "malware", "檔案鑑識"],
    featured: true,
    status: "new",
  },
  {
    slug: "pcap-summary-analyzer",
    name: "PCAP 封包摘要分析器",
    englishName: "PCAP Packet Summary Analyzer",
    description: "在瀏覽器本機讀取 classic PCAP，彙整協定、端點與前 200 筆 Ethernet／IPv4／IPv6／TCP／UDP 封包。",
    category: "鑑識與分析",
    icon: "PCAP",
    tags: ["pcap analyzer", "packet capture", "wireshark", "network forensics", "dns"],
    featured: true,
    status: "new",
    guide: {
      intro: "事件初篩不一定需要先把封包上傳或開啟完整 Wireshark。本工具直接在瀏覽器讀取 classic PCAP Global Header 與 packet records，快速呈現協定與通訊端點。",
      steps: ["選擇小於 10 MB 的 classic .pcap，或先使用內建 DNS 範例確認解析格式。", "檢查 Link Type、封包數、協定分布、熱門端點與前 200 筆 packet summary。", "需要 TCP stream 重組、PCAPNG 或深度 payload 分析時，再交由 Wireshark、Zeek 等專業工具。"],
      useCases: ["快速初篩 EDR、IDS、蜜罐或 CTF 提供的小型 PCAP。", "辨識 DNS、TCP、UDP、ICMP 與 IPv4／IPv6 通訊比例。", "在離線且不外傳封包內容的情境下找出主要來源與目的端點。"],
    },
  },
  {
    slug: "string-extractor",
    name: "檔案字串擷取器",
    englishName: "String Extractor",
    description: "從本機二進位檔擷取可列印 ASCII 字串，快速尋找 URL、路徑與可疑命令。",
    category: "鑑識與分析",
    icon: "Aa",
    tags: ["strings", "binary", "forensics", "malware analysis", "ascii"],
    featured: true,
  },
  {
    slug: "timestamp-decoder",
    name: "鑑識時間戳解碼器",
    englishName: "Forensic Timestamp Decoder",
    description: "解碼 Unix 秒／毫秒、Windows FILETIME 與 WebKit 時間，統一顯示 UTC 與台北時間。",
    category: "鑑識與分析",
    icon: "T",
    tags: ["timestamp", "unix", "filetime", "webkit", "forensics"],
    featured: true,
    status: "new",
  },
  {
    slug: "secret-scanner",
    name: "敏感資訊掃描器",
    englishName: "Secret Scanner",
    description: "從程式碼、設定檔或 Log 找出 Private Key、JWT、雲端金鑰與常見 Token，避免秘密外洩。",
    category: "威脅分析",
    icon: "!",
    tags: ["secret", "token", "api key", "credential", "leak"],
    featured: true,
    status: "new",
  },
  {
    slug: "hash-identifier",
    name: "Hash 類型辨識器",
    englishName: "Hash Identifier",
    description: "依字元集、長度與格式辨識 MD5、SHA、bcrypt、Argon2、NTLM 等常見雜湊候選。",
    category: "編碼與雜湊",
    icon: "?",
    tags: ["hash identifier", "md5", "sha", "bcrypt", "argon2"],
    featured: true,
    status: "new",
  },
  {
    slug: "hex-viewer",
    name: "本機 Hex Viewer",
    englishName: "Hex Viewer",
    description: "以 Offset、十六進位與 ASCII 三欄檢視本機檔案前 64 KB，適合快速鑑識與格式判讀。",
    category: "鑑識與分析",
    icon: "Hx",
    tags: ["hex", "binary", "forensics", "file analysis"],
    featured: true,
  },
  {
    slug: "url-risk-analyzer",
    name: "可疑 URL 分析器",
    englishName: "Suspicious URL Analyzer",
    description: "拆解網址結構並標示帳密嵌入、Punycode、IP Host、非標準 Port 與混淆風險。",
    category: "威脅分析",
    icon: "U",
    tags: ["url", "phishing", "punycode", "domain", "triage"],
    featured: true,
    status: "new",
  },
  {
    slug: "chmod-calculator",
    name: "chmod 權限計算器",
    englishName: "chmod Calculator",
    description: "在 rwx 權限與八進位模式間即時換算，並提示 world-writable、SUID、SGID 等風險。",
    category: "網路與風險",
    icon: "rwx",
    tags: ["chmod", "linux", "permissions", "suid", "unix"],
    featured: true,
  },
  { slug: "xor-tool", name: "XOR 編解碼與破解", englishName: "XOR Cipher Tool", description: "使用文字或 Hex Key 進行重複 XOR，並暴力枚舉 Single-byte XOR 的可讀結果。", category: "CTF 工具", icon: "⊕", tags: ["xor", "crypto", "single byte", "ctf"], featured: true, status: "new" },
  { slug: "caesar-bruteforce", name: "Caesar／ROT 暴力枚舉", englishName: "Caesar Cipher Brute Force", description: "一次列出 Caesar Cipher 全部 26 種位移，快速辨識 ROT13 與古典密碼明文。", category: "CTF 工具", icon: "R", tags: ["caesar", "rot13", "cipher", "ctf"], featured: true, status: "new" },
  { slug: "base-ascii-converter", name: "進位與 ASCII 轉換器", englishName: "Number Base & ASCII Converter", description: "在 Binary、Octal、Decimal、Hex 與 ASCII bytes 間轉換，支援空白分隔輸入。", category: "CTF 工具", icon: "0b", tags: ["binary", "hex", "ascii", "base", "ctf"], featured: true, status: "new" },
  { slug: "integer-packer", name: "整數 Pack／Unpack", englishName: "Integer Packing Tool", description: "將整數轉成 p16、p32、p64 的 Little／Big Endian bytes，或從 Hex 還原數值。", category: "CTF 工具", icon: "p64", tags: ["pwn", "pack", "unpack", "endian", "ctf"], featured: true, status: "new" },
  { slug: "rsa-math-helper", name: "RSA 數學助手", englishName: "RSA Math Helper", description: "計算 GCD、模反元素與快速模冪，協助 CTF RSA 題目的基礎數論運算。", category: "CTF 工具", icon: "RSA", tags: ["rsa", "gcd", "modular inverse", "powmod", "crypto"], featured: true, status: "new" },
  { slug: "unicode-escape-codec", name: "Unicode／跳脫序列工具", englishName: "Unicode Escape Codec", description: "安全編解碼 JavaScript escape、Unicode code point 與 HTML numeric entity，不執行輸入內容。", category: "CTF 工具", icon: "U+", tags: ["unicode", "escape", "javascript", "html entity", "ctf"], featured: true, status: "new", guide: {
    intro: "Unicode 與跳脫序列常被用在 JavaScript、HTML、XSS payload、惡意程式設定與 CTF 題目。本工具只把編碼還原成純文字，不會執行腳本或解析 HTML 標籤。",
    steps: ["選擇 JavaScript escape、Unicode code point 或 HTML numeric entity 格式。", "貼上要分析的跳脫序列並按解碼；也可貼入一般文字反向編碼。", "以純文字檢查結果，必要時搭配 URL Codec 或 Base64 工具繼續分層解碼。"],
    useCases: ["還原 \\u、\\x 與 \\u{...} 混淆的 JavaScript 字串。", "轉換 U+XXXX Unicode code point，辨識同形字與特殊字元。", "分析 HTML numeric entity 編碼的 XSS payload 或釣魚內容。"],
  } },
  { slug: "layered-decoder", name: "多層編碼解碼器", englishName: "Layered Encoding Decoder", description: "自動辨識並逐層還原 URL、Base64、Hex、JavaScript escape 與 HTML numeric entity，保留每一步記錄。", category: "CTF 工具", icon: "≋", tags: ["base64", "url decode", "hex", "unicode", "obfuscation", "ctf"], featured: true, status: "new", guide: {
    intro: "惡意程式字串、釣魚連結與 CTF 題目常把 URL、Base64、Hex 或 Unicode 疊加多次。本工具會在安全上限內逐層辨識，並顯示每一步採用的格式。",
    steps: ["貼上疑似多層編碼的字串，選擇最多解碼層數。", "執行後逐步檢查格式判斷與長度變化，避免把正常文字誤判為編碼。", "複製最終純文字；若仍有其他格式，可改用對應的單一編解碼工具深入分析。"],
    useCases: ["拆解 URL encoding 包住 Base64 或 Hex 的 CTF payload。", "追蹤惡意 JavaScript、PowerShell 或釣魚內容的混淆層。", "以限深度、限輸出的方式分析未知字串，避免無限解碼。"],
  } },
  { slug: "path-traversal-analyzer", name: "Path Traversal 分析器", englishName: "Path Traversal Analyzer", description: "逐層還原 percent encoding、統一 Windows／POSIX 分隔符並標示上層目錄、null byte 與解析差異風險。", category: "CTF 工具", icon: "../", tags: ["path traversal", "directory traversal", "lfi", "url decode", "web ctf"], featured: true, status: "new", guide: {
    intro: "Directory Traversal 與 LFI payload 常透過 double encoding、反斜線或 null byte 隱藏。本工具只做詞法分析，不會讀取檔案，也不會把輸入送到任何網站。",
    steps: ["貼上 URL path、Windows 路徑或可疑參數值，選擇最多 percent decoding 層數。", "檢查每層解碼結果、正規化路徑與上層目錄片段，辨識不同解析器可能看到的內容。", "依風險提示回到應用程式驗證 canonicalization、base directory 與 allowlist 邏輯。"],
    useCases: ["分析 Web Log、WAF 告警與 CTF 中的 ../、%2e%2e 或 double-encoded payload。", "比較 Windows 反斜線與 POSIX 正斜線混用造成的路徑解析差異。", "檢查 null byte、絕對路徑與越過起始目錄等 LFI 線索。"],
  } },
];

export function findTool(slug: string) {
  return toolCatalog.find((tool) => tool.slug === slug);
}
