export type ToolCategory = "編碼與雜湊" | "威脅分析" | "網路與風險" | "密碼與驗證" | "鑑識與分析";

export type ToolDefinition = {
  slug: string;
  name: string;
  englishName: string;
  description: string;
  category: ToolCategory;
  icon: string;
  tags: string[];
  featured?: boolean;
  status?: "new" | "popular";
};

export const categories: Array<{ name: ToolCategory; label: string }> = [
  { name: "編碼與雜湊", label: "ENCODE" },
  { name: "威脅分析", label: "THREAT INTEL" },
  { name: "網路與風險", label: "NETWORK" },
  { name: "密碼與驗證", label: "AUTH" },
  { name: "鑑識與分析", label: "FORENSICS" },
];

export const toolCatalog: ToolDefinition[] = [
  {
    slug: "hash-generator",
    name: "雜湊產生器",
    englishName: "Hash Generator",
    description: "快速計算 SHA-1、SHA-256、SHA-384 與 SHA-512，適合比對檔案與事件證據。",
    category: "編碼與雜湊",
    icon: "#",
    tags: ["hash", "sha256", "checksum", "雜湊"],
    featured: true,
    status: "popular",
  },
  {
    slug: "base64-codec",
    name: "Base64 編解碼",
    englishName: "Base64 Codec",
    description: "正確處理 UTF-8 中文文字的 Base64 編碼與解碼。",
    category: "編碼與雜湊",
    icon: "64",
    tags: ["base64", "encode", "decode", "編碼"],
    featured: true,
  },
  {
    slug: "url-codec",
    name: "URL 編解碼",
    englishName: "URL Codec",
    description: "安全地編碼或還原查詢字串、路徑與特殊字元。",
    category: "編碼與雜湊",
    icon: "%",
    tags: ["url", "percent encoding", "decode"],
  },
  {
    slug: "hmac-generator",
    name: "HMAC 產生器",
    englishName: "HMAC Generator",
    description: "使用本機 Web Crypto 建立 HMAC-SHA256/384/512 訊息驗證碼。",
    category: "編碼與雜湊",
    icon: "H",
    tags: ["hmac", "signature", "sha256", "api"],
  },
  {
    slug: "sri-generator",
    name: "SRI 完整性雜湊",
    englishName: "SRI Hash Generator",
    description: "為前端資源產生 Subresource Integrity sha384 屬性值。",
    category: "編碼與雜湊",
    icon: "S",
    tags: ["sri", "integrity", "frontend", "supply chain"],
    status: "new",
  },
  {
    slug: "jwt-decoder",
    name: "JWT 解碼器",
    englishName: "JWT Decoder",
    description: "在本機檢視 JWT header、payload、到期時間與常見安全警訊。",
    category: "密碼與驗證",
    icon: "J",
    tags: ["jwt", "token", "oauth", "authentication"],
    featured: true,
    status: "popular",
  },
  {
    slug: "password-generator",
    name: "安全密碼產生器",
    englishName: "Password Generator",
    description: "使用密碼學安全亂數產生器建立可自訂規則的強密碼。",
    category: "密碼與驗證",
    icon: "✦",
    tags: ["password", "random", "credential", "密碼"],
    featured: true,
  },
  {
    slug: "password-strength",
    name: "密碼強度檢查",
    englishName: "Password Strength Checker",
    description: "估算熵值並找出常見字串、重複模式與組成弱點。",
    category: "密碼與驗證",
    icon: "▰",
    tags: ["password", "entropy", "strength", "密碼強度"],
  },
  {
    slug: "ioc-extractor",
    name: "IOC 指標擷取器",
    englishName: "IOC Extractor",
    description: "從事件報告或 Log 一次擷取 IP、網域、URL、Email 與雜湊值。",
    category: "威脅分析",
    icon: "◎",
    tags: ["ioc", "ip", "domain", "hash", "threat intelligence"],
    featured: true,
    status: "popular",
  },
  {
    slug: "url-defanger",
    name: "URL Defang / Refang",
    englishName: "URL Defanger",
    description: "將可疑 URL 與 IP 去武器化，或還原分析報告中的安全格式。",
    category: "威脅分析",
    icon: "[.]",
    tags: ["defang", "refang", "url", "malware"],
    featured: true,
  },
  {
    slug: "entropy-calculator",
    name: "資料熵值計算器",
    englishName: "Entropy Calculator",
    description: "計算 Shannon entropy，協助辨識壓縮、加密或混淆內容。",
    category: "威脅分析",
    icon: "Σ",
    tags: ["entropy", "forensics", "malware", "shannon"],
  },
  {
    slug: "cidr-calculator",
    name: "IPv4 CIDR 計算器",
    englishName: "CIDR Calculator",
    description: "計算網路位址、廣播位址、遮罩、可用主機數與 IP 範圍。",
    category: "網路與風險",
    icon: "/",
    tags: ["cidr", "subnet", "ipv4", "network"],
    featured: true,
  },
  {
    slug: "cvss-calculator",
    name: "CVSS v3.1 計算器",
    englishName: "CVSS v3.1 Calculator",
    description: "依 FIRST CVSS v3.1 基礎指標計算分數、嚴重度與 Vector。",
    category: "網路與風險",
    icon: "V",
    tags: ["cvss", "vulnerability", "risk", "cve"],
    featured: true,
    status: "new",
  },
  {
    slug: "security-headers-analyzer",
    name: "安全標頭分析器",
    englishName: "Security Headers Analyzer",
    description: "貼上 HTTP response headers，檢查 CSP、HSTS、Referrer-Policy 等防護與常見設定缺口。",
    category: "網路與風險",
    icon: "H:",
    tags: ["security headers", "csp", "hsts", "http", "web security"],
    featured: true,
    status: "new",
  },
  {
    slug: "email-header-analyzer",
    name: "Email Header 分析器",
    englishName: "Email Header Analyzer",
    description: "解析郵件標頭、傳遞節點與 SPF、DKIM、DMARC 驗證結果，協助調查釣魚郵件。",
    category: "威脅分析",
    icon: "@",
    tags: ["email", "header", "spf", "dkim", "dmarc", "phishing"],
    featured: true,
    status: "new",
  },
  {
    slug: "file-signature-checker",
    name: "檔案簽章辨識器",
    englishName: "File Signature Checker",
    description: "讀取本機檔案 Magic Bytes，辨識真實格式並比對副檔名，檔案內容不會上傳。",
    category: "鑑識與分析",
    icon: "0x",
    tags: ["magic bytes", "file signature", "forensics", "malware", "檔案鑑識"],
    featured: true,
    status: "new",
  },
  {
    slug: "string-extractor",
    name: "檔案字串擷取器",
    englishName: "String Extractor",
    description: "從本機二進位檔擷取可列印 ASCII 字串，快速尋找 URL、路徑與可疑命令。",
    category: "鑑識與分析",
    icon: "Aa",
    tags: ["strings", "binary", "forensics", "malware analysis", "ascii"],
    featured: true,
  },
  {
    slug: "timestamp-decoder",
    name: "鑑識時間戳解碼器",
    englishName: "Forensic Timestamp Decoder",
    description: "解碼 Unix 秒／毫秒、Windows FILETIME 與 WebKit 時間，統一顯示 UTC 與台北時間。",
    category: "鑑識與分析",
    icon: "T",
    tags: ["timestamp", "unix", "filetime", "webkit", "forensics"],
    featured: true,
    status: "new",
  },
];

export function findTool(slug: string) {
  return toolCatalog.find((tool) => tool.slug === slug);
}
